# Generated by Django 4.1 on 2024-12-10 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataTujuan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lokasiPertama', models.CharField(max_length=200)),
                ('lokasiTujuan', models.CharField(max_length=200)),
                ('tgl_pergi', models.DateField()),
                ('tgl_pulang', models.DateField()),
            ],
        ),
    ]
