# Generated by Django 4.1 on 2024-12-10 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maskapai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nameMaskapai', models.CharField(max_length=200)),
                ('hargaTicket', models.IntegerField(max_length=200)),
            ],
        ),
    ]
