# Generated by Django 4.1 on 2024-12-10 03:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0002_maskapai'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskapai',
            name='estimasiWaktu',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='maskapai',
            name='jamBerangkat',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='maskapai',
            name='jamSampai',
            field=models.TimeField(null=True),
        ),
    ]
