# Generated by Django 4.1 on 2024-12-10 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0004_remove_maskapai_estimasiwaktu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maskapai',
            name='hargaTicket',
            field=models.DecimalField(decimal_places=3, max_digits=10),
        ),
    ]
