# Generated by Django 4.1 on 2024-12-10 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0006_alter_maskapai_hargaticket'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataTujuan',
        ),
        migrations.AddField(
            model_name='maskapai',
            name='lokasiPertama',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maskapai',
            name='lokasiTujuan',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maskapai',
            name='tgl_pergi',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='maskapai',
            name='tgl_pulang',
            field=models.DateField(null=True),
        ),
    ]
