# Generated by Django 4.1 on 2024-12-11 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0007_delete_datatujuan_maskapai_lokasipertama_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskapai',
            name='bandaraPertama',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='maskapai',
            name='bandaraTujuan',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
