# Generated by Django 4.1 on 2024-12-12 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0008_maskapai_bandarapertama_maskapai_bandaratujuan'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataPenumpang',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=200, null=True)),
                ('jenisPenerbangan', models.CharField(max_length=200)),
                ('seat_id', models.CharField(max_length=200, null=True)),
                ('waktuPembelian', models.TimeField()),
            ],
        ),
        migrations.RenameField(
            model_name='maskapai',
            old_name='tgl_pergi',
            new_name='tgl_takeoff',
        ),
        migrations.RemoveField(
            model_name='maskapai',
            name='tgl_pulang',
        ),
    ]
