# Generated by Django 4.1 on 2024-12-13 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0011_seats'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DataPenumpang',
        ),
    ]
