# Generated by Django 4.1 on 2024-12-13 07:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0012_delete_datapenumpang'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketReservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namaLengkap', models.CharField(max_length=200)),
                ('nik', models.CharField(max_length=16)),
                ('waktuPembelian', models.TimeField()),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Airlanes.seats')),
            ],
        ),
    ]
