# Generated by Django 4.1 on 2024-12-14 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0013_ticketreservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='jumlahTicket',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
