# Generated by Django 4.1 on 2024-12-14 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0014_ticketreservation_jumlahticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='maskapai',
            name='clas',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
