# Generated by Django 4.1 on 2024-12-17 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0016_remove_ticketreservation_jumlahticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketreservation',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
