# Generated by Django 4.1 on 2024-12-17 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0017_ticketreservation_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('nik_user', models.CharField(max_length=16)),
                ('maskapaiName', models.CharField(max_length=200)),
                ('takeoff_date', models.CharField(max_length=200)),
                ('class_airplane', models.CharField(max_length=200)),
                ('seat_user', models.CharField(max_length=200)),
                ('ticketPrice', models.CharField(max_length=200)),
                ('timeBuyTicket', models.CharField(max_length=200)),
            ],
        ),
    ]
