# Generated by Django 4.1 on 2024-12-17 02:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Airlanes', '0018_userticket'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userticket',
            old_name='name',
            new_name='name_user_ticket',
        ),
    ]
